
GET http://localhost:3000/

###
POST https://hameed-flw-solution.herokuapp.com/validate-rule
Content-Type: application/json


{
  "rule": {
    "field": "missions",
    "condition": "gte",
    "condition_value": "30" 
  },
  "data": {
    "name": "James Holden",
    "crew": "Rocinante",
    "age": "34",
    "position": "Captain",
    "missions": "45"
  }
}